terminate called after throwing an instance of 'std::runtime_error'
  what():  Wrong! Arguments not supported! Skipping gemm!

